name: budget_in
description: Budget In
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  currency_text_input_formatter: ^2.1.11
  dartz: ^0.10.1
  data_table_2: ^2.5.12
  dio: ^5.4.1
  dropdown_search: ^5.0.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_core: ^2.26.0
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_popup: ^3.3.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.6
  google_fonts: 6.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  lottie: ^3.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  # very_good_analysis: ^5.1.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
    - assets/svg/
    - assets/others/
    - assets/images/
    - .env
    - prod.env

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/n.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/n.png
  android_12:
    color: "#ffffff"
  web: false
  fullscreen: true
  color_dark: "#000000"
  image_dark: assets/images/n.png
