name: budget_in
description: Budget In
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.6
  firebase_core: ^2.26.0
  carousel_slider: ^4.2.1
  fl_chart: ^0.66.2

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  # very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
    - assets/svg/
    - assets/others/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
