// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfzdH7MOvBq84g2DbVUb7m169WIw0H00A',
    appId: '1:183886689490:web:eff350950e2f316895e90b',
    messagingSenderId: '183886689490',
    projectId: 'budgetin-dev',
    authDomain: 'budgetin-dev.firebaseapp.com',
    storageBucket: 'budgetin-dev.appspot.com',
    measurementId: 'G-T6BP1NP8LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFKXRCylLImh4VChIr2_Wc5tLOjDxg71M',
    appId: '1:183886689490:android:4595ef5dfc82e90a95e90b',
    messagingSenderId: '183886689490',
    projectId: 'budgetin-dev',
    storageBucket: 'budgetin-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVAoZs0baxrMamsMiDfWCdP8J7mnsucto',
    appId: '1:183886689490:ios:7bf6147b9e52091f95e90b',
    messagingSenderId: '183886689490',
    projectId: 'budgetin-dev',
    storageBucket: 'budgetin-dev.appspot.com',
    iosBundleId: 'com.budgetin.budget-in',
  );
}
