// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7WMUeKmWeWI4ocduZk2or4S_5RY1ZPzo',
    appId: '1:632357772579:web:2544cdecb0aaa528e78096',
    messagingSenderId: '632357772579',
    projectId: 'budgetin-prod',
    authDomain: 'budgetin-prod.firebaseapp.com',
    storageBucket: 'budgetin-prod.appspot.com',
    measurementId: 'G-Z3TE9C284L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxi7q6278hhqLcwz7bXlI6o8PIs-Y_YEM',
    appId: '1:632357772579:android:9b2b3bdeaa187be1e78096',
    messagingSenderId: '632357772579',
    projectId: 'budgetin-prod',
    storageBucket: 'budgetin-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBphHrwHZLBvAKUG-3fjgLvl6P-yXQ6hng',
    appId: '1:632357772579:ios:59ec7f7114afd95ce78096',
    messagingSenderId: '632357772579',
    projectId: 'budgetin-prod',
    storageBucket: 'budgetin-prod.appspot.com',
    iosBundleId: 'com.budgetin.budget-in',
  );
}
